model:
  base_learning_rate: 2.0e-06 
  target: ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    linear_start: 0.00085
    linear_end: 0.012
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: image
    cond_stage_key: caption
    image_size: 32
    channels: 4
    cond_stage_trainable: true
    conditioning_key: crossattn
    monitor: val/loss_simple_ema
    scale_factor: 0.18215
    use_ema: False

    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 32
        in_channels: 4
        out_channels: 4
        model_channels: 128
        attention_resolutions:
        - 4
        - 2
        - 1
        num_res_blocks: 2
        channel_mult:
        - 1
        - 2
        - 4
        - 4
        num_heads: 8
        use_spatial_transformer: true
        transformer_depth: 1
        context_dim: 1280
        use_checkpoint: true
        legacy: False

    first_stage_config:
      target: ldm.models.autoencoder.AutoencoderKL
      params:
        embed_dim: 4
        ckpt_path: models/first_stage_models/kl-f8/model.ckpt
        monitor: val/rec_loss
        ddconfig:
          double_z: true
          z_channels: 4
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity

    cond_stage_config:
      target: ldm.modules.encoders.modules.BERTEmbedder
      params:
        n_embed: 1280
        n_layer: 32
data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 12
    num_workers: 8
    train:
      target: ldm.data.flintstones_data.CustomTrain
      params:
        data_folder: /ubc/cs/research/shield/projects/trahman8/snap_research/flintstones_data
        cache: /ubc/cs/research/shield/projects/trahman8/snap_research/flintstones_data
        min_len: 4
        mode: train
    validation:
      target: ldm.data.flintstones_data.CustomTest
      params:
        data_folder: /ubc/cs/research/shield/projects/trahman8/snap_research/flintstones_data
        cache: /ubc/cs/research/shield/projects/trahman8/snap_research/flintstones_data
        min_len: 4 
        mode: test

