model:
  base_learning_rate: 2.0e-06 
  target: ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    linear_start: 0.00085
    linear_end: 0.012
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: image
    cond_stage_key: caption
    image_size: 64
    channels: 3
    cond_stage_trainable: true
    conditioning_key: crossattn
    monitor: val/loss_simple_ema
    scale_factor: 0.18215
    use_ema: False

    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 64
        in_channels: 3
        out_channels: 3
        model_channels: 128
        attention_resolutions:
        - 4
        - 2
        - 1
        num_res_blocks: 2
        channel_mult:
        - 1
        - 2
        - 4
        - 4
        num_heads: 8
        use_spatial_transformer: true
        transformer_depth: 1
        context_dim: 1280
        use_checkpoint: true
        legacy: False

    first_stage_config:
      target: ldm.models.autoencoder.AutoencoderKL
      params:
        embed_dim: 64
        ckpt_path: logs/2022-10-13T15-40-49_mugen_kl_8x8x64/checkpoints/epoch=000006.ckpt #models/first_stage_models/kl-f8/model.ckpt
        monitor: val/rec_loss
        ddconfig:
          double_z: true
          z_channels: 64
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 1
          - 2
          - 2
          - 4
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity

    cond_stage_config:
      target: ldm.modules.encoders.modules.BERTEmbedder
      params:
        n_embed: 1280
        n_layer: 8
data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 16 #24
    num_workers: 8
    train:
      target: ldm.data.mugen_data.CustomTrain
      params:
        training_json: /ubc/cs/research/shield/datasets/coinrun/coinrun_dataset_jsons/release/train.json
        size: 256
        get_game_frame: True
        get_text_desc: True
        get_audio: False
        split: train
        sample_every_n_frames: 12
        sequence_length: 1
        data_path: /ubc/cs/research/shield/datasets/coinrun/coinrun_dataset_jsons/release/
        use_manual_annotation: True
        resolution: 256
    validation:
      target: ldm.data.mugen_data.CustomTest
      params:
        test_json: /ubc/cs/research/shield/datasets/coinrun/coinrun_dataset_jsons/release/test.json
        size: 256
        get_game_frame: True
        get_text_desc: True
        get_audio: False
        split: test
        sample_every_n_frames: 12
        sequence_length: 1
        data_path: /ubc/cs/research/shield/datasets/coinrun/coinrun_dataset_jsons/release/
        use_manual_annotation: True
        resolution: 256

